spring.application.name=hrs

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/db_local
spring.datasource.username=user_local
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# disable transform camelcase column name to snake case
# Correct property keys
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

security.jwt.secret-key=9WWKfaWJn3mZaufLr9oVWfEHnpAzKNFcAy15Qxqn5fc
security.jwt.expiration-time=300
security.jwt.refresh.expiration.time=7200

# disable run on docker
spring.docker.compose.enabled=false

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:changelog/db.changelog-master.xml

logging.level.org.springframework.web=DEBUG

app.allowed.cors=http://127.0.0.1:4200,http://localhost:4200

app.cookie.lifetime=7200
app.cookie.samesite=None